// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDoOzuFeQJVTyJ1rQH0EXnuU39LohVqEQ',
    appId: '1:948734981608:web:88ffc6bb37be4187bda05d',
    messagingSenderId: '948734981608',
    projectId: 'crisisiq-7b8aa',
    authDomain: 'crisisiq-7b8aa.firebaseapp.com',
    storageBucket: 'crisisiq-7b8aa.firebasestorage.app',
    measurementId: 'G-KWJE6GG7QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vBDkC-eTHUL5LHF8U-JUy6zEhCwapHw',
    appId: '1:948734981608:android:48a4fe43c0fc8998bda05d',
    messagingSenderId: '948734981608',
    projectId: 'crisisiq-7b8aa',
    storageBucket: 'crisisiq-7b8aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp5p0vTbSUGnHHtKpBWhEKxvew4LlRw6c',
    appId: '1:948734981608:ios:341054e7fe62a069bda05d',
    messagingSenderId: '948734981608',
    projectId: 'crisisiq-7b8aa',
    storageBucket: 'crisisiq-7b8aa.firebasestorage.app',
    iosBundleId: 'com.example.crisisiq',
  );
}
